[package]
name = "binary_to_xml-src"
version = "0.1.0"
edition = "2024"

[dependencies]
rbx_binary = "1.0.0"
rbx_dom_weak = "3.0.0"
rbx_xml = "1.0.0"

[profile.release]  # https://github.com/johnthagen/min-sized-rust
strip = true
opt-level = "s"
lto = true
codegen-units = 1
